name: Deploy to VPS (my-portfolio-frontend)

on:
  push:
    branches:
      - main  # prod repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restrict Workflow to Specific Users
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        run: 'echo "Workflow initiated by authorized user: ${{ github.actor }}"'

      - name: Checkout code
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: actions/checkout@v3

      # Build  code in the CI environment (outside the server)
      - name: Install dependencies and build
        run: |
          cd frontend  
          npm install
          npm run build

      # Copy the built files to the VPS (you only need to copy the build files)
      - name: Copy build files to VPS
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"  # Adjust this to the build output folder
          target: "/var/www/my-portfolio/frontend"  # Target folder on the server
          port: 2200

      - name: Restart Application
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on the server
            cd /var/www/my-portfolio/frontend
            git pull origin develop  # Pull the latest code (optional, depending on your needs)
            npm install  # Install dependencies
            npm run build
          port: 2200
