name: Deploy to VPS (my-portfolio-frontend)

on:
  push:
    branches:
      - main  # prod repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restrict Workflow to Specific Users
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        run: 'echo "Workflow initiated by authorized user: ${{ github.actor }}"'

      - name: Checkout code
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: actions/checkout@v3

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install  # Install dependencies
          npm run build  # Create the build folder

      - name: List build directory contents (check for files)
        run: |
          ls -l frontend/build  # Verify the build directory exists and contains files

      - name: Copy build files to VPS
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend/build/*"  # Only copy the contents of the build folder
          target: "/var/www/my-portfolio/frontend"  # Target folder on the server
          port: 2200

      - name: Restart Application
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on the server
            cd /var/www/my-portfolio/frontend
            git pull origin main  # Pull the latest code (optional, depending on your needs)
            npm install  # Install dependencies
            npm run build  # Rebuild (if necessary)
          port: 2200
