name: Deploy to VPS (my-portfolio-frontend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restrict Workflow to Specific Users
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        run: 'echo "Workflow initiated by authorized user: ${{ github.actor }}"'

      - name: Checkout code
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: actions/checkout@v3

      - name: Build frontend
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        run: |
          cd frontend
          npm install
          npm run build  # This creates 'dist' directory instead of 'build'

      - name: Verify build output
        run: |
          ls -l frontend/dist

      - name: Copy build files to VPS
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/my-portfolio/frontend"
          port: 2200

      - name: Ensure directory exists on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/my-portfolio/frontend
          port: 2200

      - name: Restart Application
        if: ${{ github.actor == 'Iacre' || github.actor == 'EdgeReachTech' }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 77.37.124.116
          username: fiacre
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # If using Nginx
            sudo systemctl restart nginx
            
            # Or if using PM2
            # pm2 restart your-app-name
          port: 2200
